### ISSUE TITLE
Error running a toy Example

### ISSUE THREAD

**Issue by ashwathaithal** [Jorsorokin/HDBSCAN#1]
Hi 

I tried to fit HDBSCAN with default values on my toy 3D data and encountered the following error:

clusterer.run_hdbscan();
Training cluster hierarchy...
	Data matrix size:
		185 points x 3 dimensions

	Min # neighbors: 5
	Min cluster size: 5
	Min # of clusters: 1
	Skipping every 0 iteration

Error using vertcat
Dimensions of arrays being concatenated are not consistent.

Error in hdbscan_fit (line 100)
    nodes = [nodes;[1:n;1:n]']; weights = [weights;dCore']; % adds self loops

Error in HDBSCAN/fit_model (line 195)
            self.model = hdbscan_fit( self.data,...

Error in HDBSCAN/run_hdbscan (line 329)
            self.fit_model( dEps );

Any idea what is the issue?

**Comment by Jorsorokin** [comment]
​hmm I'm not receiving that issue. Can you tell me a bit about your data? I
see you have a matrix of size 185 x 3. Are they all float? integer? any
nans?

Can you set a breakpoint at that line that's erroring in hdbscan_fit.m and
tell me what the sizes of nodes, weights, and n are?

**Comment by Jorsorokin** [comment]
if you're supplying your 3D data directly this won't work. HDSBCAN will
only fit a 2D matrix currently. You can flatten out the 3rd dimension and
then try clustering

**Comment by Jorsorokin** [comment]
By 3D data I mean a tensor, which is what I assumed you meant as well

**Comment by ashwathaithal** [comment]
thanks for your quick feedback. 
my data is not tensor, it s 185x3 double matrix. (so 2D matrix).

when i first ran your code it complained about "Undefined function or variable 'sparse_to_csr'."
so i downloaded that function from https://github.com/dgleich/gaimc/blob/master/sparse_to_csr.m.

i generate the data like below: (7 clusters)
X = [gallery('uniformdata',[40 3],12)-5;...
    gallery('uniformdata',[10 3],13)-2.5;...
    gallery('uniformdata',[30 3],14)-1.25;...
    gallery('uniformdata',[25 3],15);...
    gallery('uniformdata',[15 3],16)+1.2;...
    gallery('uniformdata',[35 3],17)+2.5;...
    gallery('uniformdata',[30 3],18)+5];

run HDBCAN:
clusterer = HDBSCAN( X );
clusterer.run_hdbscan();

output:
Training cluster hierarchy...
	Data matrix size:
		185 points x 3 dimensions

	Min # neighbors: 5
	Min cluster size: 5
	Min # of clusters: 1
	Skipping every 0 iteration
Error using vertcat
Dimensions of arrays being concatenated are not consistent.

Error in hdbscan_fit (line 101)
    weights = [weights;dCore']; % adds self loops

Error in HDBSCAN/fit_model (line 195)
            self.model = hdbscan_fit( self.data,...

Error in HDBSCAN/run_hdbscan (line 329)
            self.fit_model( dEps );
 
it fails in "weights = [weights;dCore']; % adds self loops" 
because the size of "weights" is 184x1 and size of "dCore" is 185x1  
when i took out the transpose for the "dCore" it worked fine.

let me know if the fix is ok.

**Comment by Jorsorokin** [comment]
ah that's interesting... if I run on my computer the dimensions of "dCore"
are flipped (so, would be 1 x 185). So yes, removing the transpose is
appropriate. Not sure why it would be transposed when you're running it,
but glad it's figured out.

Cheers,
- jordan

**Comment by Jorsorokin** [comment]
thanks for letting me know about the "sparse_to_csr.m". This is a file that
the external file "mst_prim.m" which I've included uses, but I was unaware
of that dependency. I'll update the github repo accordingly .

**Comment by ashwathaithal** [comment]
i am running Matlab R2018a. Not sure why it would transpose the vector/matrix but may be Mathworks decided to change something :)
